//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLEngine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string trydelit {
            get {
                return ((string)(this["trydelit"]));
            }
            set {
                this["trydelit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_firstbin {
            get {
                return ((string)(this["fname_data_firstbin"]));
            }
            set {
                this["fname_data_firstbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_firstbin {
            get {
                return ((string)(this["fname_train_firstbin"]));
            }
            set {
                this["fname_train_firstbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_firstbin {
            get {
                return ((string)(this["fname_test_firstbin"]));
            }
            set {
                this["fname_test_firstbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_firstbin {
            get {
                return ((string)(this["fname_model_firstbin"]));
            }
            set {
                this["fname_model_firstbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_firstbin {
            get {
                return ((string)(this["fname_valid_firstbin"]));
            }
            set {
                this["fname_valid_firstbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_secondbin {
            get {
                return ((string)(this["fname_data_secondbin"]));
            }
            set {
                this["fname_data_secondbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_secondbin {
            get {
                return ((string)(this["fname_train_secondbin"]));
            }
            set {
                this["fname_train_secondbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_secondbin {
            get {
                return ((string)(this["fname_test_secondbin"]));
            }
            set {
                this["fname_test_secondbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_secondbin {
            get {
                return ((string)(this["fname_model_secondbin"]));
            }
            set {
                this["fname_model_secondbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_secondbin {
            get {
                return ((string)(this["fname_valid_secondbin"]));
            }
            set {
                this["fname_valid_secondbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_thirdbin {
            get {
                return ((string)(this["fname_data_thirdbin"]));
            }
            set {
                this["fname_data_thirdbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_thirdbin {
            get {
                return ((string)(this["fname_train_thirdbin"]));
            }
            set {
                this["fname_train_thirdbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_thirdbin {
            get {
                return ((string)(this["fname_test_thirdbin"]));
            }
            set {
                this["fname_test_thirdbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_thirdbin {
            get {
                return ((string)(this["fname_model_thirdbin"]));
            }
            set {
                this["fname_model_thirdbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_thirdbin {
            get {
                return ((string)(this["fname_valid_thirdbin"]));
            }
            set {
                this["fname_valid_thirdbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_fourthbin {
            get {
                return ((string)(this["fname_data_fourthbin"]));
            }
            set {
                this["fname_data_fourthbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_fourthbin {
            get {
                return ((string)(this["fname_train_fourthbin"]));
            }
            set {
                this["fname_train_fourthbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_fourthbin {
            get {
                return ((string)(this["fname_test_fourthbin"]));
            }
            set {
                this["fname_test_fourthbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_fourthbin {
            get {
                return ((string)(this["fname_model_fourthbin"]));
            }
            set {
                this["fname_model_fourthbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_fourthbin {
            get {
                return ((string)(this["fname_valid_fourthbin"]));
            }
            set {
                this["fname_valid_fourthbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_firstmulti {
            get {
                return ((string)(this["fname_data_firstmulti"]));
            }
            set {
                this["fname_data_firstmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_firstmulti {
            get {
                return ((string)(this["fname_train_firstmulti"]));
            }
            set {
                this["fname_train_firstmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_firstmulti {
            get {
                return ((string)(this["fname_test_firstmulti"]));
            }
            set {
                this["fname_test_firstmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_firstmulti {
            get {
                return ((string)(this["fname_model_firstmulti"]));
            }
            set {
                this["fname_model_firstmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_firstmulti {
            get {
                return ((string)(this["fname_valid_firstmulti"]));
            }
            set {
                this["fname_valid_firstmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_secondmulti {
            get {
                return ((string)(this["fname_data_secondmulti"]));
            }
            set {
                this["fname_data_secondmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_secondmulti {
            get {
                return ((string)(this["fname_train_secondmulti"]));
            }
            set {
                this["fname_train_secondmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_secondmulti {
            get {
                return ((string)(this["fname_test_secondmulti"]));
            }
            set {
                this["fname_test_secondmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_secondmulti {
            get {
                return ((string)(this["fname_model_secondmulti"]));
            }
            set {
                this["fname_model_secondmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_secondmulti {
            get {
                return ((string)(this["fname_valid_secondmulti"]));
            }
            set {
                this["fname_valid_secondmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_thirdmulti {
            get {
                return ((string)(this["fname_data_thirdmulti"]));
            }
            set {
                this["fname_data_thirdmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_thirdmulti {
            get {
                return ((string)(this["fname_train_thirdmulti"]));
            }
            set {
                this["fname_train_thirdmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_thirdmulti {
            get {
                return ((string)(this["fname_test_thirdmulti"]));
            }
            set {
                this["fname_test_thirdmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_thirdmulti {
            get {
                return ((string)(this["fname_model_thirdmulti"]));
            }
            set {
                this["fname_model_thirdmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_thirdmulti {
            get {
                return ((string)(this["fname_valid_thirdmulti"]));
            }
            set {
                this["fname_valid_thirdmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_fourthmulti {
            get {
                return ((string)(this["fname_data_fourthmulti"]));
            }
            set {
                this["fname_data_fourthmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_fourthmulti {
            get {
                return ((string)(this["fname_train_fourthmulti"]));
            }
            set {
                this["fname_train_fourthmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_fourthmulti {
            get {
                return ((string)(this["fname_test_fourthmulti"]));
            }
            set {
                this["fname_test_fourthmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_fourthmulti {
            get {
                return ((string)(this["fname_model_fourthmulti"]));
            }
            set {
                this["fname_model_fourthmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_fourthmulti {
            get {
                return ((string)(this["fname_valid_fourthmulti"]));
            }
            set {
                this["fname_valid_fourthmulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_firstreg {
            get {
                return ((string)(this["fname_data_firstreg"]));
            }
            set {
                this["fname_data_firstreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_firstreg {
            get {
                return ((string)(this["fname_train_firstreg"]));
            }
            set {
                this["fname_train_firstreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_firstreg {
            get {
                return ((string)(this["fname_test_firstreg"]));
            }
            set {
                this["fname_test_firstreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_firstreg {
            get {
                return ((string)(this["fname_model_firstreg"]));
            }
            set {
                this["fname_model_firstreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_firstreg {
            get {
                return ((string)(this["fname_valid_firstreg"]));
            }
            set {
                this["fname_valid_firstreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_secondreg {
            get {
                return ((string)(this["fname_data_secondreg"]));
            }
            set {
                this["fname_data_secondreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_secondreg {
            get {
                return ((string)(this["fname_train_secondreg"]));
            }
            set {
                this["fname_train_secondreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_secondreg {
            get {
                return ((string)(this["fname_test_secondreg"]));
            }
            set {
                this["fname_test_secondreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_secondreg {
            get {
                return ((string)(this["fname_model_secondreg"]));
            }
            set {
                this["fname_model_secondreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_secondreg {
            get {
                return ((string)(this["fname_valid_secondreg"]));
            }
            set {
                this["fname_valid_secondreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_thirdreg {
            get {
                return ((string)(this["fname_data_thirdreg"]));
            }
            set {
                this["fname_data_thirdreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_thirdreg {
            get {
                return ((string)(this["fname_train_thirdreg"]));
            }
            set {
                this["fname_train_thirdreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_thirdreg {
            get {
                return ((string)(this["fname_test_thirdreg"]));
            }
            set {
                this["fname_test_thirdreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_thirdreg {
            get {
                return ((string)(this["fname_model_thirdreg"]));
            }
            set {
                this["fname_model_thirdreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_thirdreg {
            get {
                return ((string)(this["fname_valid_thirdreg"]));
            }
            set {
                this["fname_valid_thirdreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_data_fourthreg {
            get {
                return ((string)(this["fname_data_fourthreg"]));
            }
            set {
                this["fname_data_fourthreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_train_fourthreg {
            get {
                return ((string)(this["fname_train_fourthreg"]));
            }
            set {
                this["fname_train_fourthreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_test_fourthreg {
            get {
                return ((string)(this["fname_test_fourthreg"]));
            }
            set {
                this["fname_test_fourthreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_model_fourthreg {
            get {
                return ((string)(this["fname_model_fourthreg"]));
            }
            set {
                this["fname_model_fourthreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fname_valid_fourthreg {
            get {
                return ((string)(this["fname_valid_fourthreg"]));
            }
            set {
                this["fname_valid_fourthreg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string models_path {
            get {
                return ((string)(this["models_path"]));
            }
            set {
                this["models_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string splitParts {
            get {
                return ((string)(this["splitParts"]));
            }
            set {
                this["splitParts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string trainTime {
            get {
                return ((string)(this["trainTime"]));
            }
            set {
                this["trainTime"] = value;
            }
        }
    }
}
